version: '2'
server:
  image: node
  working_dir: /app
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  depends_on:
      - db
  environment:
    - DATABASE_URL=postgres://user:password@db:5432/sampleapp
    - PORT=3000
db:
  image: postgres
  expose:
    - 5432
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_USER: user
    POSTGRES_DB: sampleapp